USE master
GO
--DROP DATABASE QUANLYTHUVIEN
--GO
----------------------------------TẠO DATABASE----------------------------------
CREATE DATABASE QUANLYTHUVIEN
GO
USE QUANLYTHUVIEN
GO
----------------------------------TẠO CÁC TABLE----------------------------------
CREATE TABLE	 TACGIA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	BUTDANH NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 NHAXUATBAN
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENNXB NVARCHAR(50) NOT NULL,
	SODT NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	EMAIL NVARCHAR(50) NULL,
	WEBSITE NVARCHAR(50) NULL
)
GO
CREATE TABLE	 THELOAI
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENTHELOAI NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE	 SACH
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENSACH NVARCHAR(50) NOT NULL,
	IDNXB INT NOT NULL,
	NAMXB DATETIME NOT NULL,
	IDTHELOAI INT NOT NULL,
	IDTACGIA INT NOT NULL,
	GIA FLOAT NOT NULL,
	SOLUONGSACH INT NOT NULL,
	VITRISACH NVARCHAR(20) NULL
)
GO
CREATE TABLE	 DONVI
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENDONVI NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 DOCGIA
(
	IDMASOTHE INT IDENTITY(2000,1) PRIMARY KEY,
	NGAYLAP DATE NULL,
	HANSUDUNG DATE NULL,
	IDDONVI INT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME NULL,
	GIOITINH BIT NULL,
	EMAIL NVARCHAR(50) NULL,
	SODT NCHAR(20) NULL,
	CMND NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,	
	HINHANH NCHAR(100) NULL
)
GO
CREATE TABLE	 CHUCVU
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENCHUCVU NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 TAIKHOAN
(
	EMAIL NVARCHAR(50) PRIMARY KEY,
	MATKHAU NCHAR(50) NOT NULL,
	CHUCVU INT NOT NULL
)
GO
CREATE TABLE	 NHANVIEN
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NULL,
	GIOITINH BIT NULL,
	EMAIL NVARCHAR(50) NULL,
	SODT NCHAR(20) NULL,
	CMND NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	NGAYVAOLAM DATE NULL
)
GO
CREATE TABLE	 MUONTRASACH
(
	IDMUON INT IDENTITY(1,1) PRIMARY KEY,
	IDMATHEDOCGIA INT NOT NULL,
)
CREATE TABLE CHITIETMUONTRA
(
	IDCHITIETMUON INT IDENTITY(1,1) PRIMARY KEY,
	IDMUON INT NOT NULL,
	IDSACH INT NOT NULL,
	IDTHUTHUCHOMUON INT NOT NULL,
	IDTHUTHUNHANTRA INT NULL,
	SOLUONGMUON INT NOT NULL,
	NGAYMUON DATETIME NOT NULL,
	HANTRA DATETIME NULL,
	TIENTHECHAN FLOAT NOT NULL,
	TINHTRANG BIT NOT NULL
)
GO
CREATE TABLE	 PHIEUPHAT
(
	IDPHIEU INT IDENTITY(1,1) PRIMARY KEY,
	IDCHITIETMUON INT NOT NULL,
	IDTHUTHULAPPHIEU INT NOT NULL,
	NGAYLAPPHIEU DATETIME NOT NULL,
	SONGAYQUAHAN INT NOT NULL,
	TIENPHAT FLOAT NOT NULL,
	GHICHUPHAT NVARCHAR(50) NULL
)
GO
CREATE TABLE	 MANHINH
(
	MAMANHINH INT IDENTITY(1,1) PRIMARY KEY,
	TENMANHINH NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 PHANQUYEN
(
	MAMANHINH INT NOT NULL,
	MACHUCVU INT NOT NULL,
	COQUYEN BIT NOT NULL,
	PRIMARY KEY(MAMANHINH,MACHUCVU)
)
GO
----------------------------------TẠO KHÓA NGOẠI----------------------------------
ALTER TABLE dbo.SACH
ADD FOREIGN KEY(IDNXB) REFERENCES dbo.NHAXUATBAN(ID)
GO
ALTER TABLE dbo.SACH
ADD FOREIGN KEY(IDTHELOAI) REFERENCES dbo.THELOAI(ID)
GO
ALTER TABLE dbo.SACH
ADD FOREIGN KEY(IDTACGIA) REFERENCES dbo.TACGIA(ID)
GO
ALTER TABLE dbo.DOCGIA
ADD FOREIGN KEY(IDDONVI) REFERENCES dbo.DONVI(ID)
GO
ALTER TABLE dbo.MUONTRASACH
ADD FOREIGN KEY(IDMATHEDOCGIA) REFERENCES dbo.DOCGIA(IDMASOTHE)
GO
ALTER TABLE dbo.CHITIETMUONTRA
ADD FOREIGN KEY(IDSACH) REFERENCES dbo.SACH(ID)
GO
ALTER TABLE dbo.CHITIETMUONTRA
ADD FOREIGN KEY(IDTHUTHUCHOMUON) REFERENCES dbo.NHANVIEN(ID)
GO
ALTER TABLE dbo.CHITIETMUONTRA
ADD FOREIGN KEY(IDTHUTHUNHANTRA) REFERENCES dbo.NHANVIEN(ID)
GO
ALTER TABLE dbo.CHITIETMUONTRA
ADD FOREIGN KEY(IDMUON) REFERENCES dbo.MUONTRASACH(IDMUON)
GO
ALTER TABLE dbo.PHIEUPHAT
ADD FOREIGN KEY(IDTHUTHULAPPHIEU) REFERENCES dbo.NHANVIEN(ID)
GO
ALTER TABLE dbo.PHIEUPHAT
ADD FOREIGN KEY(IDCHITIETMUON) REFERENCES dbo.CHITIETMUONTRA(IDCHITIETMUON)
GO
ALTER TABLE dbo.TAIKHOAN
ADD FOREIGN KEY(CHUCVU) REFERENCES dbo.CHUCVU(ID)
GO
ALTER TABLE dbo.NHANVIEN
ADD FOREIGN KEY(EMAIL) REFERENCES dbo.TAIKHOAN(EMAIL)
GO
ALTER TABLE dbo.PHANQUYEN
ADD FOREIGN KEY(MAMANHINH) REFERENCES dbo.MANHINH(MAMANHINH)
GO
ALTER TABLE dbo.PHANQUYEN
ADD FOREIGN KEY(MACHUCVU) REFERENCES dbo.CHUCVU(ID)
GO
----------------------------------NHẬP CSDL----------------------------------
SET DATEFORMAT DMY
GO
INSERT INTO dbo.CHUCVU
(
    TENCHUCVU
)
VALUES
(N'Quản Lý' -- TENCHUCVU - nvarchar(50)
    )
INSERT INTO dbo.CHUCVU
(
    TENCHUCVU
)
VALUES
(N'Thủ Thư' -- TENCHUCVU - nvarchar(50)
    )
GO

INSERT INTO dbo.TAIKHOAN
(
    EMAIL,
    MATKHAU,
    CHUCVU
)
VALUES
(   N'admin@gmail.com', -- EMAIL - nvarchar(50)
    N'admin@gmail.com', -- MATKHAU - nchar(50)
    1    -- CHUCVU - int
    )
INSERT INTO dbo.TAIKHOAN
(
    EMAIL,
    MATKHAU,
    CHUCVU
)
VALUES
(   N'lamchikhang.it@gmail.com', -- EMAIL - nvarchar(50)
    N'lamchikhang.it@gmail.com', -- MATKHAU - nchar(50)
    2    -- CHUCVU - int
    )
GO

INSERT INTO dbo.NHANVIEN
(
    HOTEN,
    NGAYSINH,
    GIOITINH,
    EMAIL,
    SODT,
    CMND,
    DIACHI,
    NGAYVAOLAM
)
VALUES
(   N'Khang Lâm',       -- HOTEN - nvarchar(50)
    '27/01/2001', -- NGAYSINH - datetime
    1,      -- GIOITINH - bit
    N'admin@gmail.com',       -- EMAIL - nvarchar(50)
    N'0342468501',       -- SODT - nchar(20)
    N'366313530',       -- CMND - nchar(20)
    N'Bình Tân, TP.HCM',       -- DIACHI - nvarchar(50)
    '30/04/2022'  -- NGAYVAOLAM - datetime
    )
INSERT INTO dbo.NHANVIEN
(
    HOTEN,
    NGAYSINH,
    GIOITINH,
    EMAIL,
    SODT,
    CMND,
    DIACHI,
    NGAYVAOLAM
)
VALUES
(   N'Lâm Chí Khang',       -- HOTEN - nvarchar(50)
    '27/01/2001', -- NGAYSINH - datetime
    1,      -- GIOITINH - bit
    N'lamchikhang.it@gmail.com',       -- EMAIL - nvarchar(50)
    N'0342468501',       -- SODT - nchar(20)
    N'366313530',       -- CMND - nchar(20)
    N'Bình Tân, TP.HCM',       -- DIACHI - nvarchar(50)
    '30/04/2022'  -- NGAYVAOLAM - datetime
    )

SELECT * FROM dbo.TAIKHOAN
--xem chức vụ của từng nhân viên
SELECT nv.HOTEN,nv.NGAYSINH,nv.GIOITINH,nv.EMAIL,nv.SODT,nv.CMND,nv.DIACHI,nv.NGAYVAOLAM,cv.TENCHUCVU
FROM dbo.NHANVIEN nv, dbo.CHUCVU cv, dbo.TAIKHOAN tk
WHERE tk.EMAIL = nv.EMAIL AND tk.CHUCVU = cv.ID