USE master
GO
----------------------------------TẠO DATABASE----------------------------------
CREATE DATABASE QUANLYTHUVIEN
GO
USE QUANLYTHUVIEN
GO
----------------------------------TẠO CÁC TABLE----------------------------------
CREATE TABLE	 TACGIA
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	BUTDANH NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 NHAXUATBAN
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENNXB NVARCHAR(50) NOT NULL,
	SODT NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	EMAIL NVARCHAR(50) NULL,
	WEBSITE NVARCHAR(50) NULL
)
GO
CREATE TABLE	 THELOAI
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENTHELOAI NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE	 SACH
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENSACH NVARCHAR(50) NOT NULL,
	IDNXB INT NOT NULL,
	NAMXB DATETIME NOT NULL,
	IDTHELOAI INT NOT NULL,
	GIA FLOAT NOT NULL,
	SOLUONGSACH INT NOT NULL,
	IDTACGIA INT NOT NULL,
	VITRISACH NVARCHAR(20) NULL
)
GO
CREATE TABLE	 DONVI
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENDONVI NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 DOCGIA
(
	IDMASOTHE INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME NULL,
	GIOITINH BIT NULL,
	EMAIL NVARCHAR(50) NULL,
	SODT NCHAR(20) NULL,
	CMND NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	IDDONVI INT NULL,
	HINHANH NCHAR(100) NULL
)
GO
CREATE TABLE	 THETHUVIEN
(
	IDMASOTHE INT PRIMARY KEY,
	NGAYLAP DATETIME NULL,
	HANSUDUNG DATETIME NULL
)
GO
CREATE TABLE	 CHUCVU
(
	IDCHUCVU INT IDENTITY(1,1) PRIMARY KEY,
	TENCHUCVU NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 TAIKHOAN
(
	TENTAIKHOAN NCHAR(20) PRIMARY KEY,
	MATKHAU NCHAR(50) NOT NULL,
	CHUCVU INT NOT NULL
)
GO
CREATE TABLE	 THUTHU
(
	IDTHUTHU INT IDENTITY(1,1) PRIMARY KEY,
	TENTAIKHOAN NCHAR(20) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME NULL,
	GIOITINH BIT NULL,
	EMAIL NVARCHAR(50) NULL,
	SODT NCHAR(20) NULL,
	CMND NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	NGAYBATDAU DATETIME NULL
)
GO
CREATE TABLE	 MUONTRASACH
(
	IDMUON INT IDENTITY(1,1) PRIMARY KEY,
	IDSACH INT NOT NULL,
	IDMATHEDOCGIA INT NOT NULL,
	IDTHUTHUCHOMUON INT NOT NULL,
	IDTHUTHUNHANTRA INT NULL,
	SOLUONGMUON INT NOT NULL,
	NGAYMUON DATETIME NOT NULL,
	HANTRA DATETIME NULL,
	TINHTRANG BIT NOT NULL
)
GO
CREATE TABLE	 PHIEUPHAT
(
	IDPHIEU INT IDENTITY(1,1) PRIMARY KEY,
	IDMUON INT NOT NULL,
	IDTHUTHULAPPHIEU INT NOT NULL,
	NGAYLAPPHIEU DATETIME NOT NULL,
	TIENPHAT FLOAT NOT NULL,
	GHICHUPHAT NVARCHAR(50) NULL
)
GO
CREATE TABLE	 MANHINH
(
	MAMANHINH INT IDENTITY(1,1) PRIMARY KEY,
	TENMANHINH NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE	 PHANQUYEN
(
	MAMANHINH INT NOT NULL,
	MACHUCVU INT NOT NULL,
	COQUYEN BIT NOT NULL,
	PRIMARY KEY(MAMANHINH,MACHUCVU)
)
GO
----------------------------------TẠO KHÓA NGOẠI----------------------------------
ALTER TABLE dbo.SACH
ADD FOREIGN KEY(IDNXB) REFERENCES dbo.NHAXUATBAN(ID)
GO
ALTER TABLE dbo.SACH
ADD FOREIGN KEY(IDTHELOAI) REFERENCES dbo.THELOAI(ID)
GO
ALTER TABLE dbo.SACH
ADD FOREIGN KEY(IDTACGIA) REFERENCES dbo.TACGIA(ID)
GO
ALTER TABLE dbo.DOCGIA
ADD FOREIGN KEY(IDDONVI) REFERENCES dbo.DONVI(ID)
GO
ALTER TABLE dbo.THETHUVIEN
ADD FOREIGN KEY(IDMASOTHE) REFERENCES dbo.DOCGIA(IDMASOTHE)
GO
ALTER TABLE dbo.THUTHU
ADD FOREIGN KEY(TENTAIKHOAN) REFERENCES dbo.TAIKHOAN(TENTAIKHOAN)
GO
ALTER TABLE dbo.MUONTRASACH
ADD FOREIGN KEY(IDSACH) REFERENCES dbo.SACH(ID)
GO
ALTER TABLE dbo.MUONTRASACH
ADD FOREIGN KEY(IDMATHEDOCGIA) REFERENCES dbo.DOCGIA(IDMASOTHE)
GO
ALTER TABLE dbo.MUONTRASACH
ADD FOREIGN KEY(IDTHUTHUCHOMUON) REFERENCES dbo.THUTHU(IDTHUTHU)
GO
ALTER TABLE dbo.MUONTRASACH
ADD FOREIGN KEY(IDTHUTHUNHANTRA) REFERENCES dbo.THUTHU(IDTHUTHU)
GO
ALTER TABLE dbo.PHIEUPHAT
ADD FOREIGN KEY(IDMUON) REFERENCES dbo.MUONTRASACH(IDMUON)
GO
ALTER TABLE dbo.PHIEUPHAT
ADD FOREIGN KEY(IDTHUTHULAPPHIEU) REFERENCES dbo.THUTHU(IDTHUTHU)
GO
ALTER TABLE dbo.TAIKHOAN
ADD FOREIGN KEY(CHUCVU) REFERENCES dbo.CHUCVU(IDCHUCVU)
GO
ALTER TABLE dbo.PHANQUYEN
ADD FOREIGN KEY(MAMANHINH) REFERENCES dbo.MANHINH(MAMANHINH)
GO
ALTER TABLE dbo.PHANQUYEN
ADD FOREIGN KEY(MACHUCVU) REFERENCES dbo.CHUCVU(IDCHUCVU)
GO