
namespace QuanLyThuVien
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panelChildFrom = new System.Windows.Forms.Panel();
            this.panelMenu = new System.Windows.Forms.Panel();
            this.btnGioiThieu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDangXuat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThongTinQT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnQLDocGia = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnQLMuonTra = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnQLSach = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnQLTT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panelLogo = new System.Windows.Forms.Panel();
            this.piclogo = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panelMenu.SuspendLayout();
            this.panelLogo.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.piclogo)).BeginInit();
            this.SuspendLayout();
            // 
            // panelChildFrom
            // 
            this.panelChildFrom.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelChildFrom.Location = new System.Drawing.Point(250, 0);
            this.panelChildFrom.Name = "panelChildFrom";
            this.panelChildFrom.Size = new System.Drawing.Size(1363, 702);
            this.panelChildFrom.TabIndex = 5;
            // 
            // panelMenu
            // 
            this.panelMenu.AutoScroll = true;
            this.panelMenu.BackColor = System.Drawing.Color.DodgerBlue;
            this.panelMenu.Controls.Add(this.btnGioiThieu);
            this.panelMenu.Controls.Add(this.btnDangXuat);
            this.panelMenu.Controls.Add(this.btnThongTinQT);
            this.panelMenu.Controls.Add(this.btnQLDocGia);
            this.panelMenu.Controls.Add(this.btnQLMuonTra);
            this.panelMenu.Controls.Add(this.btnQLSach);
            this.panelMenu.Controls.Add(this.btnQLTT);
            this.panelMenu.Controls.Add(this.panelLogo);
            this.panelMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelMenu.Location = new System.Drawing.Point(0, 0);
            this.panelMenu.Name = "panelMenu";
            this.panelMenu.Size = new System.Drawing.Size(250, 702);
            this.panelMenu.TabIndex = 3;
            // 
            // btnGioiThieu
            // 
            this.btnGioiThieu.AllowAnimations = true;
            this.btnGioiThieu.AllowMouseEffects = true;
            this.btnGioiThieu.AllowToggling = false;
            this.btnGioiThieu.AnimationSpeed = 200;
            this.btnGioiThieu.AutoGenerateColors = false;
            this.btnGioiThieu.AutoRoundBorders = false;
            this.btnGioiThieu.AutoSizeLeftIcon = true;
            this.btnGioiThieu.AutoSizeRightIcon = true;
            this.btnGioiThieu.BackColor = System.Drawing.Color.Transparent;
            this.btnGioiThieu.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnGioiThieu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGioiThieu.BackgroundImage")));
            this.btnGioiThieu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioiThieu.ButtonText = "GIỚI THIỆU";
            this.btnGioiThieu.ButtonTextMarginLeft = 0;
            this.btnGioiThieu.ColorContrastOnClick = 45;
            this.btnGioiThieu.ColorContrastOnHover = 45;
            this.btnGioiThieu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnGioiThieu.CustomizableEdges = borderEdges1;
            this.btnGioiThieu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGioiThieu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGioiThieu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGioiThieu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGioiThieu.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGioiThieu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGioiThieu.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnGioiThieu.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnGioiThieu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGioiThieu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGioiThieu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGioiThieu.IconMarginLeft = 11;
            this.btnGioiThieu.IconPadding = 10;
            this.btnGioiThieu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGioiThieu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGioiThieu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGioiThieu.IconSize = 25;
            this.btnGioiThieu.IdleBorderColor = System.Drawing.Color.White;
            this.btnGioiThieu.IdleBorderRadius = 30;
            this.btnGioiThieu.IdleBorderThickness = 1;
            this.btnGioiThieu.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnGioiThieu.IdleIconLeftImage = null;
            this.btnGioiThieu.IdleIconRightImage = null;
            this.btnGioiThieu.IndicateFocus = false;
            this.btnGioiThieu.Location = new System.Drawing.Point(0, 372);
            this.btnGioiThieu.Name = "btnGioiThieu";
            this.btnGioiThieu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGioiThieu.OnDisabledState.BorderRadius = 30;
            this.btnGioiThieu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioiThieu.OnDisabledState.BorderThickness = 1;
            this.btnGioiThieu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGioiThieu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGioiThieu.OnDisabledState.IconLeftImage = null;
            this.btnGioiThieu.OnDisabledState.IconRightImage = null;
            this.btnGioiThieu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnGioiThieu.onHoverState.BorderRadius = 30;
            this.btnGioiThieu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioiThieu.onHoverState.BorderThickness = 1;
            this.btnGioiThieu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnGioiThieu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGioiThieu.onHoverState.IconLeftImage = null;
            this.btnGioiThieu.onHoverState.IconRightImage = null;
            this.btnGioiThieu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnGioiThieu.OnIdleState.BorderRadius = 30;
            this.btnGioiThieu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioiThieu.OnIdleState.BorderThickness = 1;
            this.btnGioiThieu.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnGioiThieu.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnGioiThieu.OnIdleState.IconLeftImage = null;
            this.btnGioiThieu.OnIdleState.IconRightImage = null;
            this.btnGioiThieu.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnGioiThieu.OnPressedState.BorderRadius = 30;
            this.btnGioiThieu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGioiThieu.OnPressedState.BorderThickness = 1;
            this.btnGioiThieu.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnGioiThieu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGioiThieu.OnPressedState.IconLeftImage = null;
            this.btnGioiThieu.OnPressedState.IconRightImage = null;
            this.btnGioiThieu.Size = new System.Drawing.Size(250, 45);
            this.btnGioiThieu.TabIndex = 8;
            this.btnGioiThieu.Tag = "0";
            this.btnGioiThieu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGioiThieu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGioiThieu.TextMarginLeft = 0;
            this.btnGioiThieu.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnGioiThieu.UseDefaultRadiusAndThickness = true;
            this.btnGioiThieu.Click += new System.EventHandler(this.btnGioiThieu_Click);
            // 
            // btnDangXuat
            // 
            this.btnDangXuat.AllowAnimations = true;
            this.btnDangXuat.AllowMouseEffects = true;
            this.btnDangXuat.AllowToggling = false;
            this.btnDangXuat.AnimationSpeed = 200;
            this.btnDangXuat.AutoGenerateColors = false;
            this.btnDangXuat.AutoRoundBorders = false;
            this.btnDangXuat.AutoSizeLeftIcon = true;
            this.btnDangXuat.AutoSizeRightIcon = true;
            this.btnDangXuat.BackColor = System.Drawing.Color.Transparent;
            this.btnDangXuat.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDangXuat.BackgroundImage")));
            this.btnDangXuat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.ButtonText = "ĐĂNG XUẤT";
            this.btnDangXuat.ButtonTextMarginLeft = 0;
            this.btnDangXuat.ColorContrastOnClick = 45;
            this.btnDangXuat.ColorContrastOnHover = 45;
            this.btnDangXuat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnDangXuat.CustomizableEdges = borderEdges2;
            this.btnDangXuat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDangXuat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnDangXuat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDangXuat.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnDangXuat.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnDangXuat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDangXuat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDangXuat.IconMarginLeft = 11;
            this.btnDangXuat.IconPadding = 10;
            this.btnDangXuat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDangXuat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDangXuat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDangXuat.IconSize = 25;
            this.btnDangXuat.IdleBorderColor = System.Drawing.Color.White;
            this.btnDangXuat.IdleBorderRadius = 30;
            this.btnDangXuat.IdleBorderThickness = 1;
            this.btnDangXuat.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.IdleIconLeftImage = null;
            this.btnDangXuat.IdleIconRightImage = null;
            this.btnDangXuat.IndicateFocus = false;
            this.btnDangXuat.Location = new System.Drawing.Point(0, 657);
            this.btnDangXuat.Name = "btnDangXuat";
            this.btnDangXuat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDangXuat.OnDisabledState.BorderRadius = 30;
            this.btnDangXuat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnDisabledState.BorderThickness = 1;
            this.btnDangXuat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDangXuat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDangXuat.OnDisabledState.IconLeftImage = null;
            this.btnDangXuat.OnDisabledState.IconRightImage = null;
            this.btnDangXuat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnDangXuat.onHoverState.BorderRadius = 30;
            this.btnDangXuat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.onHoverState.BorderThickness = 1;
            this.btnDangXuat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnDangXuat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.onHoverState.IconLeftImage = null;
            this.btnDangXuat.onHoverState.IconRightImage = null;
            this.btnDangXuat.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnDangXuat.OnIdleState.BorderRadius = 30;
            this.btnDangXuat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnIdleState.BorderThickness = 1;
            this.btnDangXuat.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnDangXuat.OnIdleState.IconLeftImage = null;
            this.btnDangXuat.OnIdleState.IconRightImage = null;
            this.btnDangXuat.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnPressedState.BorderRadius = 30;
            this.btnDangXuat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDangXuat.OnPressedState.BorderThickness = 1;
            this.btnDangXuat.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnDangXuat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDangXuat.OnPressedState.IconLeftImage = null;
            this.btnDangXuat.OnPressedState.IconRightImage = null;
            this.btnDangXuat.Size = new System.Drawing.Size(250, 45);
            this.btnDangXuat.TabIndex = 6;
            this.btnDangXuat.Tag = "0";
            this.btnDangXuat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDangXuat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDangXuat.TextMarginLeft = 0;
            this.btnDangXuat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDangXuat.UseDefaultRadiusAndThickness = true;
            this.btnDangXuat.Click += new System.EventHandler(this.btnDangXuat_Click);
            // 
            // btnThongTinQT
            // 
            this.btnThongTinQT.AllowAnimations = true;
            this.btnThongTinQT.AllowMouseEffects = true;
            this.btnThongTinQT.AllowToggling = false;
            this.btnThongTinQT.AnimationSpeed = 200;
            this.btnThongTinQT.AutoGenerateColors = false;
            this.btnThongTinQT.AutoRoundBorders = false;
            this.btnThongTinQT.AutoSizeLeftIcon = true;
            this.btnThongTinQT.AutoSizeRightIcon = true;
            this.btnThongTinQT.BackColor = System.Drawing.Color.Transparent;
            this.btnThongTinQT.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnThongTinQT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThongTinQT.BackgroundImage")));
            this.btnThongTinQT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTinQT.ButtonText = "THÔNG TIN BẢN THÂN";
            this.btnThongTinQT.ButtonTextMarginLeft = 0;
            this.btnThongTinQT.ColorContrastOnClick = 45;
            this.btnThongTinQT.ColorContrastOnHover = 45;
            this.btnThongTinQT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnThongTinQT.CustomizableEdges = borderEdges3;
            this.btnThongTinQT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThongTinQT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongTinQT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongTinQT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongTinQT.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnThongTinQT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThongTinQT.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnThongTinQT.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnThongTinQT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThongTinQT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThongTinQT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThongTinQT.IconMarginLeft = 11;
            this.btnThongTinQT.IconPadding = 10;
            this.btnThongTinQT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThongTinQT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThongTinQT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThongTinQT.IconSize = 25;
            this.btnThongTinQT.IdleBorderColor = System.Drawing.Color.White;
            this.btnThongTinQT.IdleBorderRadius = 30;
            this.btnThongTinQT.IdleBorderThickness = 1;
            this.btnThongTinQT.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnThongTinQT.IdleIconLeftImage = null;
            this.btnThongTinQT.IdleIconRightImage = null;
            this.btnThongTinQT.IndicateFocus = false;
            this.btnThongTinQT.Location = new System.Drawing.Point(0, 327);
            this.btnThongTinQT.Name = "btnThongTinQT";
            this.btnThongTinQT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThongTinQT.OnDisabledState.BorderRadius = 30;
            this.btnThongTinQT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTinQT.OnDisabledState.BorderThickness = 1;
            this.btnThongTinQT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThongTinQT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThongTinQT.OnDisabledState.IconLeftImage = null;
            this.btnThongTinQT.OnDisabledState.IconRightImage = null;
            this.btnThongTinQT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnThongTinQT.onHoverState.BorderRadius = 30;
            this.btnThongTinQT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTinQT.onHoverState.BorderThickness = 1;
            this.btnThongTinQT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnThongTinQT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThongTinQT.onHoverState.IconLeftImage = null;
            this.btnThongTinQT.onHoverState.IconRightImage = null;
            this.btnThongTinQT.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnThongTinQT.OnIdleState.BorderRadius = 30;
            this.btnThongTinQT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTinQT.OnIdleState.BorderThickness = 1;
            this.btnThongTinQT.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThongTinQT.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnThongTinQT.OnIdleState.IconLeftImage = null;
            this.btnThongTinQT.OnIdleState.IconRightImage = null;
            this.btnThongTinQT.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnThongTinQT.OnPressedState.BorderRadius = 30;
            this.btnThongTinQT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThongTinQT.OnPressedState.BorderThickness = 1;
            this.btnThongTinQT.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnThongTinQT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThongTinQT.OnPressedState.IconLeftImage = null;
            this.btnThongTinQT.OnPressedState.IconRightImage = null;
            this.btnThongTinQT.Size = new System.Drawing.Size(250, 45);
            this.btnThongTinQT.TabIndex = 5;
            this.btnThongTinQT.Tag = "0";
            this.btnThongTinQT.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThongTinQT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThongTinQT.TextMarginLeft = 0;
            this.btnThongTinQT.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnThongTinQT.UseDefaultRadiusAndThickness = true;
            this.btnThongTinQT.Click += new System.EventHandler(this.btnThongTinQT_Click);
            // 
            // btnQLDocGia
            // 
            this.btnQLDocGia.AllowAnimations = true;
            this.btnQLDocGia.AllowMouseEffects = true;
            this.btnQLDocGia.AllowToggling = false;
            this.btnQLDocGia.AnimationSpeed = 200;
            this.btnQLDocGia.AutoGenerateColors = false;
            this.btnQLDocGia.AutoRoundBorders = false;
            this.btnQLDocGia.AutoSizeLeftIcon = true;
            this.btnQLDocGia.AutoSizeRightIcon = true;
            this.btnQLDocGia.BackColor = System.Drawing.Color.Transparent;
            this.btnQLDocGia.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnQLDocGia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnQLDocGia.BackgroundImage")));
            this.btnQLDocGia.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLDocGia.ButtonText = "QUẢN LÝ ĐỘC GIẢ";
            this.btnQLDocGia.ButtonTextMarginLeft = 0;
            this.btnQLDocGia.ColorContrastOnClick = 45;
            this.btnQLDocGia.ColorContrastOnHover = 45;
            this.btnQLDocGia.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnQLDocGia.CustomizableEdges = borderEdges4;
            this.btnQLDocGia.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnQLDocGia.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLDocGia.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLDocGia.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLDocGia.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnQLDocGia.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnQLDocGia.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnQLDocGia.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLDocGia.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLDocGia.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLDocGia.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnQLDocGia.IconMarginLeft = 11;
            this.btnQLDocGia.IconPadding = 10;
            this.btnQLDocGia.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnQLDocGia.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLDocGia.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnQLDocGia.IconSize = 25;
            this.btnQLDocGia.IdleBorderColor = System.Drawing.Color.White;
            this.btnQLDocGia.IdleBorderRadius = 30;
            this.btnQLDocGia.IdleBorderThickness = 1;
            this.btnQLDocGia.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLDocGia.IdleIconLeftImage = null;
            this.btnQLDocGia.IdleIconRightImage = null;
            this.btnQLDocGia.IndicateFocus = false;
            this.btnQLDocGia.Location = new System.Drawing.Point(0, 282);
            this.btnQLDocGia.Name = "btnQLDocGia";
            this.btnQLDocGia.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLDocGia.OnDisabledState.BorderRadius = 30;
            this.btnQLDocGia.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLDocGia.OnDisabledState.BorderThickness = 1;
            this.btnQLDocGia.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLDocGia.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLDocGia.OnDisabledState.IconLeftImage = null;
            this.btnQLDocGia.OnDisabledState.IconRightImage = null;
            this.btnQLDocGia.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLDocGia.onHoverState.BorderRadius = 30;
            this.btnQLDocGia.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLDocGia.onHoverState.BorderThickness = 1;
            this.btnQLDocGia.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLDocGia.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnQLDocGia.onHoverState.IconLeftImage = null;
            this.btnQLDocGia.onHoverState.IconRightImage = null;
            this.btnQLDocGia.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnQLDocGia.OnIdleState.BorderRadius = 30;
            this.btnQLDocGia.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLDocGia.OnIdleState.BorderThickness = 1;
            this.btnQLDocGia.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLDocGia.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLDocGia.OnIdleState.IconLeftImage = null;
            this.btnQLDocGia.OnIdleState.IconRightImage = null;
            this.btnQLDocGia.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnQLDocGia.OnPressedState.BorderRadius = 30;
            this.btnQLDocGia.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLDocGia.OnPressedState.BorderThickness = 1;
            this.btnQLDocGia.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLDocGia.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnQLDocGia.OnPressedState.IconLeftImage = null;
            this.btnQLDocGia.OnPressedState.IconRightImage = null;
            this.btnQLDocGia.Size = new System.Drawing.Size(250, 45);
            this.btnQLDocGia.TabIndex = 4;
            this.btnQLDocGia.Tag = "2";
            this.btnQLDocGia.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLDocGia.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnQLDocGia.TextMarginLeft = 0;
            this.btnQLDocGia.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnQLDocGia.UseDefaultRadiusAndThickness = true;
            this.btnQLDocGia.Click += new System.EventHandler(this.btnQLDocGia_Click);
            // 
            // btnQLMuonTra
            // 
            this.btnQLMuonTra.AllowAnimations = true;
            this.btnQLMuonTra.AllowMouseEffects = true;
            this.btnQLMuonTra.AllowToggling = false;
            this.btnQLMuonTra.AnimationSpeed = 200;
            this.btnQLMuonTra.AutoGenerateColors = false;
            this.btnQLMuonTra.AutoRoundBorders = false;
            this.btnQLMuonTra.AutoSizeLeftIcon = true;
            this.btnQLMuonTra.AutoSizeRightIcon = true;
            this.btnQLMuonTra.BackColor = System.Drawing.Color.Transparent;
            this.btnQLMuonTra.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnQLMuonTra.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnQLMuonTra.BackgroundImage")));
            this.btnQLMuonTra.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLMuonTra.ButtonText = "QUẢN LÝ TRẢ SÁCH";
            this.btnQLMuonTra.ButtonTextMarginLeft = 0;
            this.btnQLMuonTra.ColorContrastOnClick = 45;
            this.btnQLMuonTra.ColorContrastOnHover = 45;
            this.btnQLMuonTra.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnQLMuonTra.CustomizableEdges = borderEdges5;
            this.btnQLMuonTra.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnQLMuonTra.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLMuonTra.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLMuonTra.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLMuonTra.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnQLMuonTra.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnQLMuonTra.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnQLMuonTra.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLMuonTra.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLMuonTra.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLMuonTra.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnQLMuonTra.IconMarginLeft = 11;
            this.btnQLMuonTra.IconPadding = 10;
            this.btnQLMuonTra.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnQLMuonTra.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLMuonTra.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnQLMuonTra.IconSize = 25;
            this.btnQLMuonTra.IdleBorderColor = System.Drawing.Color.White;
            this.btnQLMuonTra.IdleBorderRadius = 30;
            this.btnQLMuonTra.IdleBorderThickness = 1;
            this.btnQLMuonTra.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLMuonTra.IdleIconLeftImage = null;
            this.btnQLMuonTra.IdleIconRightImage = null;
            this.btnQLMuonTra.IndicateFocus = false;
            this.btnQLMuonTra.Location = new System.Drawing.Point(0, 237);
            this.btnQLMuonTra.Name = "btnQLMuonTra";
            this.btnQLMuonTra.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLMuonTra.OnDisabledState.BorderRadius = 30;
            this.btnQLMuonTra.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLMuonTra.OnDisabledState.BorderThickness = 1;
            this.btnQLMuonTra.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLMuonTra.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLMuonTra.OnDisabledState.IconLeftImage = null;
            this.btnQLMuonTra.OnDisabledState.IconRightImage = null;
            this.btnQLMuonTra.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLMuonTra.onHoverState.BorderRadius = 30;
            this.btnQLMuonTra.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLMuonTra.onHoverState.BorderThickness = 1;
            this.btnQLMuonTra.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLMuonTra.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnQLMuonTra.onHoverState.IconLeftImage = null;
            this.btnQLMuonTra.onHoverState.IconRightImage = null;
            this.btnQLMuonTra.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnQLMuonTra.OnIdleState.BorderRadius = 30;
            this.btnQLMuonTra.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLMuonTra.OnIdleState.BorderThickness = 1;
            this.btnQLMuonTra.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLMuonTra.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLMuonTra.OnIdleState.IconLeftImage = null;
            this.btnQLMuonTra.OnIdleState.IconRightImage = null;
            this.btnQLMuonTra.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnQLMuonTra.OnPressedState.BorderRadius = 30;
            this.btnQLMuonTra.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLMuonTra.OnPressedState.BorderThickness = 1;
            this.btnQLMuonTra.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLMuonTra.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnQLMuonTra.OnPressedState.IconLeftImage = null;
            this.btnQLMuonTra.OnPressedState.IconRightImage = null;
            this.btnQLMuonTra.Size = new System.Drawing.Size(250, 45);
            this.btnQLMuonTra.TabIndex = 3;
            this.btnQLMuonTra.Tag = "2";
            this.btnQLMuonTra.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLMuonTra.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnQLMuonTra.TextMarginLeft = 0;
            this.btnQLMuonTra.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnQLMuonTra.UseDefaultRadiusAndThickness = true;
            this.btnQLMuonTra.Click += new System.EventHandler(this.btnQLMuonTra_Click);
            // 
            // btnQLSach
            // 
            this.btnQLSach.AllowAnimations = true;
            this.btnQLSach.AllowMouseEffects = true;
            this.btnQLSach.AllowToggling = false;
            this.btnQLSach.AnimationSpeed = 200;
            this.btnQLSach.AutoGenerateColors = false;
            this.btnQLSach.AutoRoundBorders = false;
            this.btnQLSach.AutoSizeLeftIcon = true;
            this.btnQLSach.AutoSizeRightIcon = true;
            this.btnQLSach.BackColor = System.Drawing.Color.Transparent;
            this.btnQLSach.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnQLSach.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnQLSach.BackgroundImage")));
            this.btnQLSach.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLSach.ButtonText = "QUẢN LÝ SÁCH";
            this.btnQLSach.ButtonTextMarginLeft = 0;
            this.btnQLSach.ColorContrastOnClick = 45;
            this.btnQLSach.ColorContrastOnHover = 45;
            this.btnQLSach.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnQLSach.CustomizableEdges = borderEdges6;
            this.btnQLSach.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnQLSach.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLSach.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLSach.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLSach.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnQLSach.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnQLSach.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnQLSach.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLSach.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLSach.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLSach.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnQLSach.IconMarginLeft = 11;
            this.btnQLSach.IconPadding = 10;
            this.btnQLSach.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnQLSach.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLSach.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnQLSach.IconSize = 25;
            this.btnQLSach.IdleBorderColor = System.Drawing.Color.White;
            this.btnQLSach.IdleBorderRadius = 30;
            this.btnQLSach.IdleBorderThickness = 1;
            this.btnQLSach.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLSach.IdleIconLeftImage = null;
            this.btnQLSach.IdleIconRightImage = null;
            this.btnQLSach.IndicateFocus = false;
            this.btnQLSach.Location = new System.Drawing.Point(0, 192);
            this.btnQLSach.Name = "btnQLSach";
            this.btnQLSach.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLSach.OnDisabledState.BorderRadius = 30;
            this.btnQLSach.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLSach.OnDisabledState.BorderThickness = 1;
            this.btnQLSach.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLSach.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLSach.OnDisabledState.IconLeftImage = null;
            this.btnQLSach.OnDisabledState.IconRightImage = null;
            this.btnQLSach.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLSach.onHoverState.BorderRadius = 30;
            this.btnQLSach.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLSach.onHoverState.BorderThickness = 1;
            this.btnQLSach.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLSach.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnQLSach.onHoverState.IconLeftImage = null;
            this.btnQLSach.onHoverState.IconRightImage = null;
            this.btnQLSach.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnQLSach.OnIdleState.BorderRadius = 30;
            this.btnQLSach.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLSach.OnIdleState.BorderThickness = 1;
            this.btnQLSach.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLSach.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLSach.OnIdleState.IconLeftImage = null;
            this.btnQLSach.OnIdleState.IconRightImage = null;
            this.btnQLSach.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnQLSach.OnPressedState.BorderRadius = 30;
            this.btnQLSach.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLSach.OnPressedState.BorderThickness = 1;
            this.btnQLSach.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLSach.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnQLSach.OnPressedState.IconLeftImage = null;
            this.btnQLSach.OnPressedState.IconRightImage = null;
            this.btnQLSach.Size = new System.Drawing.Size(250, 45);
            this.btnQLSach.TabIndex = 2;
            this.btnQLSach.Tag = "2";
            this.btnQLSach.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLSach.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnQLSach.TextMarginLeft = 0;
            this.btnQLSach.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnQLSach.UseDefaultRadiusAndThickness = true;
            this.btnQLSach.Click += new System.EventHandler(this.btnQLSach_Click);
            // 
            // btnQLTT
            // 
            this.btnQLTT.AllowAnimations = true;
            this.btnQLTT.AllowMouseEffects = true;
            this.btnQLTT.AllowToggling = false;
            this.btnQLTT.AnimationSpeed = 200;
            this.btnQLTT.AutoGenerateColors = false;
            this.btnQLTT.AutoRoundBorders = false;
            this.btnQLTT.AutoSizeLeftIcon = true;
            this.btnQLTT.AutoSizeRightIcon = true;
            this.btnQLTT.BackColor = System.Drawing.Color.Transparent;
            this.btnQLTT.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnQLTT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnQLTT.BackgroundImage")));
            this.btnQLTT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLTT.ButtonText = "QUẢN LÝ THỦ THƯ";
            this.btnQLTT.ButtonTextMarginLeft = 0;
            this.btnQLTT.ColorContrastOnClick = 45;
            this.btnQLTT.ColorContrastOnHover = 45;
            this.btnQLTT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnQLTT.CustomizableEdges = borderEdges7;
            this.btnQLTT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnQLTT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLTT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLTT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLTT.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnQLTT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnQLTT.Font = new System.Drawing.Font("Times New Roman", 10.20895F, System.Drawing.FontStyle.Bold);
            this.btnQLTT.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLTT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLTT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLTT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnQLTT.IconMarginLeft = 11;
            this.btnQLTT.IconPadding = 10;
            this.btnQLTT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnQLTT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnQLTT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnQLTT.IconSize = 25;
            this.btnQLTT.IdleBorderColor = System.Drawing.Color.White;
            this.btnQLTT.IdleBorderRadius = 30;
            this.btnQLTT.IdleBorderThickness = 1;
            this.btnQLTT.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLTT.IdleIconLeftImage = null;
            this.btnQLTT.IdleIconRightImage = null;
            this.btnQLTT.IndicateFocus = false;
            this.btnQLTT.Location = new System.Drawing.Point(0, 147);
            this.btnQLTT.Name = "btnQLTT";
            this.btnQLTT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnQLTT.OnDisabledState.BorderRadius = 30;
            this.btnQLTT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLTT.OnDisabledState.BorderThickness = 1;
            this.btnQLTT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnQLTT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnQLTT.OnDisabledState.IconLeftImage = null;
            this.btnQLTT.OnDisabledState.IconRightImage = null;
            this.btnQLTT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLTT.onHoverState.BorderRadius = 30;
            this.btnQLTT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLTT.onHoverState.BorderThickness = 1;
            this.btnQLTT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(91)))), ((int)(((byte)(168)))), ((int)(((byte)(234)))));
            this.btnQLTT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnQLTT.onHoverState.IconLeftImage = null;
            this.btnQLTT.onHoverState.IconRightImage = null;
            this.btnQLTT.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnQLTT.OnIdleState.BorderRadius = 30;
            this.btnQLTT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLTT.OnIdleState.BorderThickness = 1;
            this.btnQLTT.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLTT.OnIdleState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnQLTT.OnIdleState.IconLeftImage = null;
            this.btnQLTT.OnIdleState.IconRightImage = null;
            this.btnQLTT.OnPressedState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnQLTT.OnPressedState.BorderRadius = 30;
            this.btnQLTT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnQLTT.OnPressedState.BorderThickness = 1;
            this.btnQLTT.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnQLTT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnQLTT.OnPressedState.IconLeftImage = null;
            this.btnQLTT.OnPressedState.IconRightImage = null;
            this.btnQLTT.Size = new System.Drawing.Size(250, 45);
            this.btnQLTT.TabIndex = 1;
            this.btnQLTT.Tag = "1";
            this.btnQLTT.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnQLTT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnQLTT.TextMarginLeft = 0;
            this.btnQLTT.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnQLTT.UseDefaultRadiusAndThickness = true;
            this.btnQLTT.Click += new System.EventHandler(this.btnQLTT_Click);
            // 
            // panelLogo
            // 
            this.panelLogo.BackColor = System.Drawing.Color.DodgerBlue;
            this.panelLogo.Controls.Add(this.piclogo);
            this.panelLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelLogo.Location = new System.Drawing.Point(0, 0);
            this.panelLogo.Name = "panelLogo";
            this.panelLogo.Size = new System.Drawing.Size(250, 147);
            this.panelLogo.TabIndex = 0;
            // 
            // piclogo
            // 
            this.piclogo.AllowFocused = false;
            this.piclogo.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.piclogo.AutoSizeHeight = true;
            this.piclogo.BackColor = System.Drawing.Color.White;
            this.piclogo.BorderRadius = 67;
            this.piclogo.Image = global::QuanLyThuVien.Properties.Resources.logohufi;
            this.piclogo.IsCircle = true;
            this.piclogo.Location = new System.Drawing.Point(51, 6);
            this.piclogo.Name = "piclogo";
            this.piclogo.Size = new System.Drawing.Size(135, 135);
            this.piclogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.piclogo.TabIndex = 0;
            this.piclogo.TabStop = false;
            this.piclogo.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1613, 702);
            this.Controls.Add(this.panelChildFrom);
            this.Controls.Add(this.panelMenu);
            this.Name = "frmMain";
            this.ShowIcon = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản Lý Thư Viện";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmMain_FormClosing);
            this.Load += new System.EventHandler(this.frmMain_Load);
            this.panelMenu.ResumeLayout(false);
            this.panelLogo.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.piclogo)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelChildFrom;
        private System.Windows.Forms.Panel panelMenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnQLTT;
        private System.Windows.Forms.Panel panelLogo;
        private Bunifu.UI.WinForms.BunifuPictureBox piclogo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGioiThieu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDangXuat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThongTinQT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnQLDocGia;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnQLMuonTra;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnQLSach;
    }
}

