<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYTHUVIEN" Class="QuanLyThuVienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THANHLONG\SQLEXPRESS;Initial Catalog=QUANLYTHUVIEN;Persist Security Info=True;User ID=sa" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QUANLYTHUVIENConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETMUONTRA" Member="CHITIETMUONTRAs">
    <Type Name="CHITIETMUONTRA">
      <Column Name="IDCHITIETMUON" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDMUON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDSACH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTHUTHUCHOMUON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTHUTHUNHANTRA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONGMUON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="HANTRA" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TIENTHECHAN" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TINHTRANG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CHITIETMUONTRA_PHIEUPHAT" Member="PHIEUPHATs" ThisKey="IDCHITIETMUON" OtherKey="IDCHITIETMUON" Type="PHIEUPHAT" />
      <Association Name="MUONTRASACH_CHITIETMUONTRA" Member="MUONTRASACH" ThisKey="IDMUON" OtherKey="IDMUON" Type="MUONTRASACH" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETMUONTRA" Member="NHANVIEN" ThisKey="IDTHUTHUCHOMUON" OtherKey="ID" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETMUONTRA1" Member="NHANVIEN1" ThisKey="IDTHUTHUNHANTRA" OtherKey="ID" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="SACH_CHITIETMUONTRA" Member="SACH" ThisKey="IDSACH" OtherKey="ID" Type="SACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THELOAI" Member="THELOAIs">
    <Type Name="THELOAI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTHELOAI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="THELOAI_SACH" Member="SACHes" ThisKey="ID" OtherKey="IDTHELOAI" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENCHUCVU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CHUCVU_PHANQUYEN" Member="PHANQUYENs" ThisKey="ID" OtherKey="MACHUCVU" Type="PHANQUYEN" />
      <Association Name="CHUCVU_TAIKHOAN" Member="TAIKHOANs" ThisKey="ID" OtherKey="CHUCVU" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.DOCGIA" Member="DOCGIAs">
    <Type Name="DOCGIA">
      <Column Name="IDMASOTHE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HANSUDUNG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IDDONVI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="DOCGIA_MUONTRASACH" Member="MUONTRASACHes" ThisKey="IDMASOTHE" OtherKey="IDMATHEDOCGIA" Type="MUONTRASACH" />
      <Association Name="DONVI_DOCGIA" Member="DONVI" ThisKey="IDDONVI" OtherKey="ID" Type="DONVI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONVI" Member="DONVIs">
    <Type Name="DONVI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDONVI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DONVI_DOCGIA" Member="DOCGIAs" ThisKey="ID" OtherKey="IDDONVI" Type="DOCGIA" />
    </Type>
  </Table>
  <Table Name="dbo.MANHINH" Member="MANHINHs">
    <Type Name="MANHINH">
      <Column Name="MAMANHINH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENMANHINH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MANHINH_PHANQUYEN" Member="PHANQUYENs" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.MUONTRASACH" Member="MUONTRASACHes">
    <Type Name="MUONTRASACH">
      <Column Name="IDMUON" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDMATHEDOCGIA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MUONTRASACH_CHITIETMUONTRA" Member="CHITIETMUONTRAs" ThisKey="IDMUON" OtherKey="IDMUON" Type="CHITIETMUONTRA" />
      <Association Name="DOCGIA_MUONTRASACH" Member="DOCGIA" ThisKey="IDMATHEDOCGIA" OtherKey="IDMASOTHE" Type="DOCGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SODT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYVAOLAM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NHANVIEN_CHITIETMUONTRA" Member="CHITIETMUONTRAs" ThisKey="ID" OtherKey="IDTHUTHUCHOMUON" Type="CHITIETMUONTRA" />
      <Association Name="NHANVIEN_CHITIETMUONTRA1" Member="CHITIETMUONTRAs1" ThisKey="ID" OtherKey="IDTHUTHUNHANTRA" Type="CHITIETMUONTRA" />
      <Association Name="NHANVIEN_PHIEUPHAT" Member="PHIEUPHATs" ThisKey="ID" OtherKey="IDTHUTHULAPPHIEU" Type="PHIEUPHAT" />
    </Type>
  </Table>
  <Table Name="dbo.NHAXUATBAN" Member="NHAXUATBANs">
    <Type Name="NHAXUATBAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SODT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WEBSITE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="NHAXUATBAN_SACH" Member="SACHes" ThisKey="ID" OtherKey="IDNXB" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="MAMANHINH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MACHUCVU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CHUCVU_PHANQUYEN" Member="CHUCVU" ThisKey="MACHUCVU" OtherKey="ID" Type="CHUCVU" IsForeignKey="true" />
      <Association Name="MANHINH_PHANQUYEN" Member="MANHINH" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="MANHINH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUPHAT" Member="PHIEUPHATs">
    <Type Name="PHIEUPHAT">
      <Column Name="IDPHIEU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IDCHITIETMUON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTHUTHULAPPHIEU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAPPHIEU" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SONGAYQUAHAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TIENPHAT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GHICHUPHAT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CHITIETMUONTRA_PHIEUPHAT" Member="CHITIETMUONTRA" ThisKey="IDCHITIETMUON" OtherKey="IDCHITIETMUON" Type="CHITIETMUONTRA" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUPHAT" Member="NHANVIEN" ThisKey="IDTHUTHULAPPHIEU" OtherKey="ID" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SACH" Member="SACHes">
    <Type Name="SACH">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDNXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAMXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTHELOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTACGIA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONGSACH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VITRISACH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HINHSACH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="SACH_CHITIETMUONTRA" Member="CHITIETMUONTRAs" ThisKey="ID" OtherKey="IDSACH" Type="CHITIETMUONTRA" />
      <Association Name="NHAXUATBAN_SACH" Member="NHAXUATBAN" ThisKey="IDNXB" OtherKey="ID" Type="NHAXUATBAN" IsForeignKey="true" />
      <Association Name="THELOAI_SACH" Member="THELOAI" ThisKey="IDTHELOAI" OtherKey="ID" Type="THELOAI" IsForeignKey="true" />
      <Association Name="TACGIA_SACH" Member="TACGIA" ThisKey="IDTACGIA" OtherKey="ID" Type="TACGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BUTDANH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TACGIA_SACH" Member="SACHes" ThisKey="ID" OtherKey="IDTACGIA" Type="SACH" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CHUCVU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CHUCVU_TAIKHOAN" Member="CHUCVU1" ThisKey="CHUCVU" OtherKey="ID" Type="CHUCVU" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.timSachTheoTen" Method="timSachTheoTen">
    <Parameter Name="tenSach" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="timSachTheoTenResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IDNXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NAMXB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTHELOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDTACGIA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONGSACH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VITRISACH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HINHSACH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>